# Generated by Django 5.1.2 on 2024-10-14 03:44

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', banjo.models.StringField(default='')),
                ('truth', banjo.models.BooleanField(default=False)),
                ('dare', banjo.models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
