# Generated by Django 5.1.2 on 2024-10-18 00:37

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tod_check_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='tod',
            name='archive',
            field=banjo.models.BooleanField(default=False),
        ),
    ]
