# Generated by Django 5.1.2 on 2024-10-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tod_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tod',
            old_name='archive',
            new_name='reject',
        ),
    ]
