# Generated by Django 5.1.2 on 2024-10-23 04:56

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_archive_tod_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tod',
            name='must_complete',
            field=banjo.models.BooleanField(default=False),
        ),
    ]
